### ISSUE TITLE
please stop breaking the API

### ISSUE THREAD

**Issue by c-cube** [mackwic/To.ml#42]
It's very annoying. I miss the conversion functions from the previous version (`Toml.Value.To.{string,int,...}` namely).

**Comment by Emm** [comment]
I understand it can be annoying. However, the API change is largely due to the negative reaction following the breaking "abstractisation" change of v2 (and largely goes back to the v1 API). Considering that the data structure is once again non-abstract, what do you feel a return of conversion functions would bring? I'll point that by comparison, the go-to module of JSON handling in OCaml (Yojson) has no such functions.

I'll also point out the existence of `Toml.of_key_values` which lets you build TOML maps out of tables in a fairly painless way (or at least, as painless as possible considering the lack of syntaxic sugar in OCaml).

**Comment by c-cube** [comment]
It's fine if it doesn't keep on changing, really. `TomlTypes` looks good to me, it's straightforward. Conversion functions are still nice for convenience (e.g., if I expect an int, `get_int : value -> int` with an exception is very convenient; also, constructor functions). I understand that lenses are supposed to help but I think they are for more advanced usage.

I agree that the new API is simpler, though, thanks for the work.

**Comment by Emm** [comment]
The only thing I'm still unhappy about is the datetime handling (the
current float representation sucks), so this may break in the future.

What we could do in the future would be to reintroduce conversion functions
in the guise of a `Toml.Unsafe` module. Lenses are great if you have
deeply-nested data, but if you're rolling with mostly flat data structures,
they're too verbose.

**Comment by c-cube** [comment]
Sounds good.
